version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Starting Frontend Sync to S3..."
      - aws s3 sync ./front-end/ s3://frontend-stack-2586 --delete --acl public-read
  post_build:
    commands:
      - echo "Frontend deployment completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: 'front-end'